services:
  - type: web
    name: unique-jms
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jms.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/unique_jms
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: unique-jms-db
    databaseName: unique_jms
    user: unique_jms_user
    plan: free