services:
  - type: web
    name: unique-jms
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jms.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: jms.settings_prod
      - key: DATABASE_URL
        fromDatabase:
          name: unique-jms-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: unique-jms-db
    databaseName: unique_jms
    user: unique_jms_user
    plan: free